# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.act_api import ActApi  # noqa: E501
from swagger_client.rest import ApiException


class TestActApi(unittest.TestCase):
    """ActApi unit test stubs"""

    def setUp(self):
        self.api = ActApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_act(self):
        """Test case for delete_act

        """
        pass

    def test_get_act(self):
        """Test case for get_act

        """
        pass

    def test_post_act(self):
        """Test case for post_act

        """
        pass

    def test_update_act(self):
        """Test case for update_act

        """
        pass


if __name__ == '__main__':
    unittest.main()
