# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.musicsound_api import MusicsoundApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMusicsoundApi(unittest.TestCase):
    """MusicsoundApi unit test stubs"""

    def setUp(self):
        self.api = MusicsoundApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_musicsound(self):
        """Test case for delete_musicsound

        """
        pass

    def test_get_musicsound(self):
        """Test case for get_musicsound

        """
        pass

    def test_post_musicsound(self):
        """Test case for post_musicsound

        """
        pass

    def test_update_musicsound(self):
        """Test case for update_musicsound

        """
        pass


if __name__ == '__main__':
    unittest.main()
