# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.metadata_api import MetadataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_metadata(self):
        """Test case for delete_metadata

        """
        pass

    def test_get_metadata(self):
        """Test case for get_metadata

        """
        pass

    def test_post_metadata(self):
        """Test case for post_metadata

        """
        pass

    def test_update_metadata(self):
        """Test case for update_metadata

        """
        pass


if __name__ == '__main__':
    unittest.main()
