# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.character_api import CharacterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCharacterApi(unittest.TestCase):
    """CharacterApi unit test stubs"""

    def setUp(self):
        self.api = CharacterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_character(self):
        """Test case for delete_character

        """
        pass

    def test_get_character(self):
        """Test case for get_character

        """
        pass

    def test_post_character(self):
        """Test case for post_character

        """
        pass

    def test_update_character(self):
        """Test case for update_character

        """
        pass


if __name__ == '__main__':
    unittest.main()
