# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.revisionhistory_api import RevisionhistoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRevisionhistoryApi(unittest.TestCase):
    """RevisionhistoryApi unit test stubs"""

    def setUp(self):
        self.api = RevisionhistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_revisionhistory(self):
        """Test case for delete_revisionhistory

        """
        pass

    def test_get_revisionhistory(self):
        """Test case for get_revisionhistory

        """
        pass

    def test_post_revisionhistory(self):
        """Test case for post_revisionhistory

        """
        pass

    def test_update_revisionhistory(self):
        """Test case for update_revisionhistory

        """
        pass


if __name__ == '__main__':
    unittest.main()
