# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.characterrelationship_api import CharacterrelationshipApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCharacterrelationshipApi(unittest.TestCase):
    """CharacterrelationshipApi unit test stubs"""

    def setUp(self):
        self.api = CharacterrelationshipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_charcterrelationship(self):
        """Test case for delete_charcterrelationship

        """
        pass

    def test_get_characterrelationship(self):
        """Test case for get_characterrelationship

        """
        pass

    def test_post_characterrelationship(self):
        """Test case for post_characterrelationship

        """
        pass

    def test_update_characterrelationship(self):
        """Test case for update_characterrelationship

        """
        pass


if __name__ == '__main__':
    unittest.main()
