# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.script_api import ScriptApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScriptApi(unittest.TestCase):
    """ScriptApi unit test stubs"""

    def setUp(self):
        self.api = ScriptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_script(self):
        """Test case for delete_script

        """
        pass

    def test_get_script(self):
        """Test case for get_script

        """
        pass

    def test_post_script(self):
        """Test case for post_script

        """
        pass

    def test_update_script(self):
        """Test case for update_script

        """
        pass


if __name__ == '__main__':
    unittest.main()
