# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.titlepage_api import TitlepageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTitlepageApi(unittest.TestCase):
    """TitlepageApi unit test stubs"""

    def setUp(self):
        self.api = TitlepageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_titlepage(self):
        """Test case for delete_titlepage

        """
        pass

    def test_get_titlepage(self):
        """Test case for get_titlepage

        """
        pass

    def test_post_titlepage(self):
        """Test case for post_titlepage

        """
        pass

    def test_update_titlepage(self):
        """Test case for update_titlepage

        """
        pass


if __name__ == '__main__':
    unittest.main()
