# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.formattingrules_api import FormattingrulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFormattingrulesApi(unittest.TestCase):
    """FormattingrulesApi unit test stubs"""

    def setUp(self):
        self.api = FormattingrulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_formattingrules(self):
        """Test case for delete_formattingrules

        """
        pass

    def test_get_formattingrules(self):
        """Test case for get_formattingrules

        """
        pass

    def test_post_formattingrules(self):
        """Test case for post_formattingrules

        """
        pass

    def test_update_forattingrules(self):
        """Test case for update_forattingrules

        """
        pass


if __name__ == '__main__':
    unittest.main()
