# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pagebreak_api import PagebreakApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPagebreakApi(unittest.TestCase):
    """PagebreakApi unit test stubs"""

    def setUp(self):
        self.api = PagebreakApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_pagebreak(self):
        """Test case for delete_pagebreak

        """
        pass

    def test_get_pagebreak(self):
        """Test case for get_pagebreak

        """
        pass

    def test_post_pagebreak(self):
        """Test case for post_pagebreak

        """
        pass

    def test_update_pagebreak(self):
        """Test case for update_pagebreak

        """
        pass


if __name__ == '__main__':
    unittest.main()
