# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dialogue_api import DialogueApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDialogueApi(unittest.TestCase):
    """DialogueApi unit test stubs"""

    def setUp(self):
        self.api = DialogueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_dialogue(self):
        """Test case for delete_dialogue

        """
        pass

    def test_get_dialogue(self):
        """Test case for get_dialogue

        """
        pass

    def test_post_dialogue(self):
        """Test case for post_dialogue

        """
        pass

    def test_update_dialogue(self):
        """Test case for update_dialogue

        """
        pass


if __name__ == '__main__':
    unittest.main()
