# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.centeredtext_api import CenteredtextApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCenteredtextApi(unittest.TestCase):
    """CenteredtextApi unit test stubs"""

    def setUp(self):
        self.api = CenteredtextApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_centeredtext(self):
        """Test case for delete_centeredtext

        """
        pass

    def test_get_centeredtext(self):
        """Test case for get_centeredtext

        """
        pass

    def test_post_centeredtext(self):
        """Test case for post_centeredtext

        """
        pass

    def test_update_centerredtext(self):
        """Test case for update_centerredtext

        """
        pass


if __name__ == '__main__':
    unittest.main()
