openapi: 3.0.1
info:
  title: SpokenWord API
  description: API to manage SpokenWord entities and their cross-references in a scriptwriting application.
  version: 1.0.0
servers:
  - url: 'https://api.yourdomain.com/v1'
paths:
  /spokenWords:
    get:
      summary: Get a list of SpokenWords
      operationId: getSpokenWords
      responses:
        '200':
          description: A list of SpokenWords
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpokenWord'
    post:
      summary: Create a new SpokenWord
      operationId: createSpokenWord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpokenWord'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpokenWord'
  /spokenWords/{id}:
    get:
      summary: Get a SpokenWord by ID
      operationId: getSpokenWordById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A SpokenWord object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpokenWord'
    put:
      summary: Update a SpokenWord
      operationId: updateSpokenWord
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpokenWord'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpokenWord'
    delete:
      summary: Delete a SpokenWord
      operationId: deleteSpokenWord
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
  /crossReferences:
    post:
      summary: Create a new CrossReference
      operationId: createCrossReference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrossReference'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrossReference'
components:
  schemas:
    SpokenWord:
      type: object
      required:
        - dialogueId
        - text
        - sequence
      properties:
        dialogueId:
          type: integer
        text:
          type: string
        sequence:
          type: integer
    CrossReference:
      type: object
      required:
        - referenceId
        - sourceElementId
        - targetType
      properties:
        referenceId:
          type: integer
        sourceElementId:
          type: integer
        targetType:
          type: string
          enum: [one, all, namedEntity]
        targetId:
          type: integer
          nullable: true
        description:
          type: string
