# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.action_api import ActionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestActionApi(unittest.TestCase):
    """ActionApi unit test stubs"""

    def setUp(self):
        self.api = ActionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_action(self):
        """Test case for delete_action

        """
        pass

    def test_get_action(self):
        """Test case for get_action

        """
        pass

    def test_post_action(self):
        """Test case for post_action

        """
        pass

    def test_update_action(self):
        """Test case for update_action

        """
        pass


if __name__ == '__main__':
    unittest.main()
