# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scenelocation_api import ScenelocationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScenelocationApi(unittest.TestCase):
    """ScenelocationApi unit test stubs"""

    def setUp(self):
        self.api = ScenelocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_scenelocation(self):
        """Test case for delete_scenelocation

        """
        pass

    def test_get_scenelocation(self):
        """Test case for get_scenelocation

        """
        pass

    def test_post_scenelocation(self):
        """Test case for post_scenelocation

        """
        pass

    def test_update_scenelocation(self):
        """Test case for update_scenelocation

        """
        pass


if __name__ == '__main__':
    unittest.main()
