# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scene_api import SceneApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSceneApi(unittest.TestCase):
    """SceneApi unit test stubs"""

    def setUp(self):
        self.api = SceneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_scene(self):
        """Test case for delete_scene

        """
        pass

    def test_get_scene(self):
        """Test case for get_scene

        """
        pass

    def test_post_scene(self):
        """Test case for post_scene

        """
        pass

    def test_update_scene(self):
        """Test case for update_scene

        """
        pass


if __name__ == '__main__':
    unittest.main()
