# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.casting_api import CastingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCastingApi(unittest.TestCase):
    """CastingApi unit test stubs"""

    def setUp(self):
        self.api = CastingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_casting(self):
        """Test case for delete_casting

        """
        pass

    def test_get_casting(self):
        """Test case for get_casting

        """
        pass

    def test_post_casting(self):
        """Test case for post_casting

        """
        pass

    def test_update_casting(self):
        """Test case for update_casting

        """
        pass


if __name__ == '__main__':
    unittest.main()
