# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.parenthetical import Parenthetical  # noqa: E501
from swagger_client.rest import ApiException


class TestParenthetical(unittest.TestCase):
    """Parenthetical unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParenthetical(self):
        """Test Parenthetical"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.parenthetical.Parenthetical()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
