# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parenthetical_api import ParentheticalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParentheticalApi(unittest.TestCase):
    """ParentheticalApi unit test stubs"""

    def setUp(self):
        self.api = ParentheticalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_parenthetical(self):
        """Test case for delete_parenthetical

        """
        pass

    def test_get_parenthetical(self):
        """Test case for get_parenthetical

        """
        pass

    def test_post_parenthetical(self):
        """Test case for post_parenthetical

        """
        pass

    def test_update_parenthetical(self):
        """Test case for update_parenthetical

        """
        pass


if __name__ == '__main__':
    unittest.main()
