# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transition_api import TransitionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransitionApi(unittest.TestCase):
    """TransitionApi unit test stubs"""

    def setUp(self):
        self.api = TransitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_transition(self):
        """Test case for delete_transition

        """
        pass

    def test_get_transition(self):
        """Test case for get_transition

        """
        pass

    def test_post_transition(self):
        """Test case for post_transition

        """
        pass

    def test_update_transition(self):
        """Test case for update_transition

        """
        pass


if __name__ == '__main__':
    unittest.main()
