# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.extendednotesresearch_api import ExtendednotesresearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExtendednotesresearchApi(unittest.TestCase):
    """ExtendednotesresearchApi unit test stubs"""

    def setUp(self):
        self.api = ExtendednotesresearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_extendednotesresearch(self):
        """Test case for delete_extendednotesresearch

        """
        pass

    def test_get_extentednotesresearch(self):
        """Test case for get_extentednotesresearch

        """
        pass

    def test_post_extendednotesresearch(self):
        """Test case for post_extendednotesresearch

        """
        pass

    def test_update_extedednotesresearch(self):
        """Test case for update_extedednotesresearch

        """
        pass


if __name__ == '__main__':
    unittest.main()
