# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.props_api import PropsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPropsApi(unittest.TestCase):
    """PropsApi unit test stubs"""

    def setUp(self):
        self.api = PropsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_props(self):
        """Test case for delete_props

        """
        pass

    def test_get_props(self):
        """Test case for get_props

        """
        pass

    def test_post_props(self):
        """Test case for post_props

        """
        pass

    def test_update_props(self):
        """Test case for update_props

        """
        pass


if __name__ == '__main__':
    unittest.main()
