# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sectionheading_api import SectionheadingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSectionheadingApi(unittest.TestCase):
    """SectionheadingApi unit test stubs"""

    def setUp(self):
        self.api = SectionheadingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_sectionheading(self):
        """Test case for delete_sectionheading

        """
        pass

    def test_get_sectionheading(self):
        """Test case for get_sectionheading

        """
        pass

    def test_post_sectionheading(self):
        """Test case for post_sectionheading

        """
        pass

    def test_update_sectionheading(self):
        """Test case for update_sectionheading

        """
        pass


if __name__ == '__main__':
    unittest.main()
