# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.crossreferences_api import CrossreferencesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCrossreferencesApi(unittest.TestCase):
    """CrossreferencesApi unit test stubs"""

    def setUp(self):
        self.api = CrossreferencesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_crossreferences(self):
        """Test case for delete_crossreferences

        """
        pass

    def test_get_crossreferences(self):
        """Test case for get_crossreferences

        """
        pass

    def test_post_crossreferences(self):
        """Test case for post_crossreferences

        """
        pass

    def test_update_crossreferences(self):
        """Test case for update_crossreferences

        """
        pass


if __name__ == '__main__':
    unittest.main()
