# coding: utf-8

"""
    PostgREST API

    This is a dynamic API generated by PostgREST  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.playwright_api import PlaywrightApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaywrightApi(unittest.TestCase):
    """PlaywrightApi unit test stubs"""

    def setUp(self):
        self.api = PlaywrightApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_playwright(self):
        """Test case for delete_playwright

        """
        pass

    def test_get_playwrights_by_id(self):
        """Test case for get_playwrights_by_id

        """
        pass

    def test_post_playwright(self):
        """Test case for post_playwright

        """
        pass

    def test_update_playwright(self):
        """Test case for update_playwright

        """
        pass


if __name__ == '__main__':
    unittest.main()
